services:
  app:
    build:
      context: .
      # 開発環境用にビルドせずにコンテナを起動する設定
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # ホストの現在のディレクトリを /app にマウント（コード変更が即反映）
      - .:/app
      # node_modules はホスト側の内容で上書きされないように匿名ボリュームで管理
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nextauth
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    # 開発用のコマンド。Next.js の開発サーバー（ホットリロード）を起動する
    command: sh -c "npx prisma generate && npm run dev"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nextauth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
