services:
  app:
    build:
      context: .
      # 開発環境用にビルドせずにコンテナを起動する設定
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      # node_modules を先にマウント
      - /app/node_modules
      # その後でホストのディレクトリをマウント
      - .:/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nextauth
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    # パッケージの存在確認を追加
    command: >
      sh -c "
        if [ ! -d node_modules/@auth ]; then
          echo 'Installing missing packages...'
          npm install
        fi &&
        npx prisma generate &&
        npm run dev
      "
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nextauth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
